- name: Sweatshirt
  price: $50
  description: Heavy Sweatshirt
  image: http://store.beboldstreetministries.org/spree/products/36/small/SS-BB-Cross.jpg?1526014613
  link: http://store.beboldstreetministries.org/products/hope-dealer-sweat-shirt

- name: V-neck
  price: $25
  description: Grey Woman's V-neck
  image: http://store.beboldstreetministries.org/spree/products/47/small/black-W-BB-cross.jpg?1526015272
  link: http://store.beboldstreetministries.org/products/woman-s-v-neck

- name: Muscle
  price: $25
  description: Grey Muscle Shirt
  image: http://store.beboldstreetministries.org/spree/products/51/small/Grey-M-HD.jpg?1526015462
  link: http://store.beboldstreetministries.org/products/grey-muscle-shirt
